### ISSUE TITLE
global: support 'irn' queries

### ISSUE THREAD

**Issue by chris-asl** [inspirehep/inspire-query-parser#65]
@michamos informed me of a new keyword we need to support, that is `irn`. 
An example query is `find irn 5988462`, this operator adds support for searching `SPIRES` identifiers. 

These are stored inside `external_system_identifiers` when `schema = SPIRES`.

**Comment by michamos** [comment]
More generally, it would be good to have a look at https://github.com/inspirehep/invenio/blob/dbfc419175b0662d0af7eafaf2c2c8a4331dd417/modules/websearch/lib/search_engine_query_parser.py#L437-L671.

**Comment by michamos** [comment]
not all of them are for literature, though.
