### ISSUE TITLE
support type code queries

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspire-query-parser#79]
Type code should support the following codes:
`tc b` : should map to `book`
`tc bookchapter` : should map to `book chapter`
`tc c` : should map to `article`

`tc note` : should map to `note`
`tc proceedings` : should map to `proceedings`
`tc t` : should map to `thesis`

@michamos can you pls check whether the above is correct? 

 Do we also need to support the following? 
`tc core` : When the schema contains core=true
`tc p` : When the schema contains refereed= true 

Is there a mapping for the existing:
i | Introductory and l | Lectures ?

Is there a mapping for the new doc types:
- activity report
- conference paper
- report
?

**Comment by michamos** [comment]
The help pages mention

value | meaning
--|--
b | Book
bookchapter | Book chapter
c | Conference paper
core | work concerning HEP
i | Introductory
l | Lectures
note | experimental note
p | Published (in a refereed journal)
proceedings | collected volume of a conference proceedings
r | Review
t | Thesis

I think it makes sense to do the following.

* Special cases:

value | record
-- | --
b | `document_type: book`
c | `document_type: conference paper`
core | `core: true`
i | `publication_type: introductory`
l | `publication_type: lectures`
p | `refereed: true`
r | `publication_type: review`
t | `document_type: thesis`

* For the rest, search in `document_type` and `publication_type` discarding spaces, which would capture the other documented and undocumented cases.
